version: '3'
services:
  backend:
    image: 'express-js'
    container_name: shopingreen-express-js
    build:
      context: ./backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
    environment:
      - SERVER_PORT=3000
      - DB_USER=root
      - DB_PASSWORD=pass
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=shopingreen
    networks:
      - shopingreen-network

  db:
    image: 'mongo'
    container_name: shopingreen-mongo
    ports:
      - '27017:27017'
    volumes:
      - database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: shopingreen
    networks:
      - shopingreen-network

  db-manager:
    image: mongo-express
    container_name: shopingreen-mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@db:27017/
    depends_on:
      - db
    networks:
      - shopingreen-network

  frontend:
    image: 'react-js'
    container_name: sopingreen-react-js
    stdin_open: true
    build:
      context: ./frontend
    ports:
      - '5500:3000'
    networks:
      - shopingreen-network

volumes:
  database:

networks:
  shopingreen-network:
