services:
  backend:
    image: eatingreen-express
    container_name: eatingreen-express
    build:
      context: ./app/backend
      target: runtime
    ports:
      - '$BACKEND_PORT:3000'
    volumes:
      - ./app/backend/logs:/app/logs
    environment:
      - NODE_ENV=production
      - SERVER_PORT=3000
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=db
      - DB_PORT=$DB_PORT
      - DB_NAME=eatingreen
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - eatingreen-network

  db:
    image: 'mongo'
    container_name: eatingreen-mongo
    ports:
      - '$DB_PORT:27017'
    volumes:
      - db:/data/db
    environment:
      MONGO_INITDB_DATABASE: eatingreen
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
    networks:
      - eatingreen-network

  frontend:
    image: eatingreen-react
    container_name: eatingreen-react
    build:
      context: ./app/frontend
      target: runtime
    ports:
      - '$FRONTEND_PORT:80'
    networks:
      - eatingreen-network

volumes:
  db:

networks:
  eatingreen-network:
