services:
  backend:
    image: shopingreen-express
    container_name: shopingreen-express
    build:
      context: ./backend
    ports:
      - '3030:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - SERVER_PORT=3000
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=shopingreen
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - shopingreen-network

  db:
    image: 'mongo'
    container_name: shopingreen-mongo
    ports:
      - '27017:27017'
    volumes:
      - database:/data/db
    environment:
      MONGO_INITDB_DATABASE: shopingreen
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
    networks:
      - shopingreen-network

  frontend:
    image: shopingreen-react
    container_name: shopingreen-react
    build:
      context: ./frontend
    ports:
      - '5000:3000'
    depends_on:
      - backend
    networks:
      - shopingreen-network

volumes:
  database:

networks:
  shopingreen-network:
