name: eatingreen
services:
  proxy:
    image: eatingreen/nginx
    container_name: eatingreen-proxy
    build:
      context: app/proxy
    ports:
      - $APP_PORT:80
    environment:
      - HOST=$APP_HOST
      - PORT=80
      - FRONTEND_HOST=frontend
      - FRONTEND_PORT=80
      - BACKEND_HOST=backend
      - BACKEND_PORT=3000
      - BACKEND_API_PATH=/api
    networks:
      - app-network

  frontend:
    image: eatingreen/react
    container_name: eatingreen-frontend
    build:
      context: app/frontend
      dockerfile: dockerfile
      target: deploy
    expose:
      - 80
    networks:
      - app-network

  backend:
    image: eatingreen/express
    container_name: eatingreen-backend
    build:
      context: app/backend
      dockerfile: dockerfile
      target: deploy
    expose:
      - 3000
    volumes:
      - ./app/backend/logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=27017
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=eatingreen
      - JWT_SECRET_KEY=$JWT_SECRET_KEY
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    container_name: eatingreen-db
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: eatingreen
    networks:
      - app-network

volumes:
  db:

networks:
  app-network:
