version: '3'
services:
  backend:
    image: 'express-js'
    container_name: shopingreen-express
    build:
      context: ./backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
    environment:
      - SERVER_PORT=3000
      - DB_USER=root
      - DB_PASSWORD=pass
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=shopingreen
    depends_on:
      - db
    networks:
      - shopingreen-network

  db:
    image: 'mongo'
    container_name: shopingreen-mongo
    ports:
      - '27017:27017'
    volumes:
      - database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: shopingreen
    networks:
      - shopingreen-network

  frontend:
    image: 'react-js'
    container_name: shopingreen-react
    build:
      context: ./frontend
    ports:
      - '5500:3000'
    networks:
      - shopingreen-network

volumes:
  database:

networks:
  shopingreen-network:
