user nginx;
worker_processes auto;

events {
  worker_connections 2048;
}

http {
  server {
    listen ${SERVER_PORT};
    server_name ${SERVER_NAME};

    location / {
      proxy_pass http://${FRONTEND_HOST}:${FRONTEND_PORT};

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location ${BACKEND_PATH} {
      rewrite ^${BACKEND_PATH}$ / break;
      rewrite ^${BACKEND_PATH}/(.*)$ /$1 break;
      proxy_pass http://${BACKEND_HOST}:${BACKEND_PORT};

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}