FROM node:20 AS build

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . ./

RUN pnpm run build
# --------------------------------
FROM node:20-alpine AS deploy

WORKDIR /app

RUN npm install -g pnpm

COPY --from=build /app/package.json /app/pnpm-lock.yaml ./
RUN pnpm install --prod --frozen-lockfile

COPY --from=build /app/dist dist/

RUN adduser -D appuser
USER appuser

ENTRYPOINT ["pnpm", "start"]
