FROM node:20-alpine AS build

WORKDIR /app

COPY ./package*.json ./
RUN npm install

COPY ./ ./

RUN npm run build
# -------------------------------------------
FROM node:20-alpine AS deploy

WORKDIR /app

COPY ./package*.json ./
RUN npm clean-install --only=production

COPY --from=build /app/dist ./dist

ENTRYPOINT ["npm", "start"]
