user nginx;
worker_processes auto;

events {
  worker_connections 2048;
}

http {
  upstream frontend {
    server ${FRONTEND_HOST}:${FRONTEND_PORT};
  }
  upstream backend {
    server ${BACKEND_HOST}:${BACKEND_PORT};
  }

  proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=app_cache:10m max_size=500m inactive=60m;

  server {
    listen ${PORT};
    server_name ${HOST};

    location / {
      proxy_pass http://frontend;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location ${BACKEND_API_PATH} {
      rewrite ^${BACKEND_API_PATH}$ / break;
      rewrite ^${BACKEND_API_PATH}/(.*)$ /$1 break;

      proxy_pass http://backend;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}