name: Linters

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  backend-linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create .env file
      run: |
        echo APP_PORT=80 >> .env
        echo DB_PORT=27017 >> .env
        echo DB_USER=root >> .env
        echo DB_PASSWORD=pass >> .env
        echo JWT_SECRET_KEY=aazesqfdgmqrzesqldfkjg >> .env

    - name: Setup services
      run: docker compose -f docker-compose.dev.yml up backend db -d

    - name: Run tests
      run: docker exec eatingreen-express npm run linter

    - name: Stop services
      run: docker compose down

  frontend-linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run linter